export const Flight = {
    SEARCH_FLIGHT: "SEARCH_FLIGHT",
    BOOK_FLIGHT_SUCCESS: "BOOK_FLIGHT_SUCCESS",
    CREATE_FLIGHT_SUCCESS: "CREATE_FLIGHT_SUCCESS"
}

export const Loader = {
  TRACK_LOADER: "TRACK_LOADER",
  OPEN_MODAL: "OPEN_MODAL",
  CLOSE_MODAL: "CLOSE_MODAL"
} 

export const User = {
  LOGIN_SUCCESSFUl: "LOGIN_SUCCESSFUl",
  SIGNUP_SUCCESSFUl: "SIGNUP_SUCCESSFUl",
  FETCH_USER: "FETCH_USER",
  UPDATE_USER: "UPDATE_USER",
  GET_RESERVATIONS: "GET_RESERVATIONS",
  CANCEL_RESERVATION: "CANCEL_RESERVATION",
  LOGOUT: "LOGOUT"
}

  